name: DevSecOps CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: devsecops-java-app
  K8S_NAMESPACE: default    # You can change namespace

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3
    - name: debug repository
      run: ls -R

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build Java Application
      run: mvn clean package -DskipTests
      working-directory: app

    - name: Build Docker Image
      run: docker build -t ${{ env.ECR_REPOSITORY }}:latest .

    - name: Run Trivy Security Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.ECR_REPOSITORY }}:latest
        format: table
        exit-code: 0           

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Tag Docker Image
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        docker tag $ECR_REPOSITORY:latest $ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPOSITORY:latest

    - name: Push Docker Image to ECR
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        docker push $ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPOSITORY:latest

    # ----------------- Kubernetes Deployment -----------------
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.30.0'

    - name: Configure kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    - name: Update Kubernetes Deployment
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        IMAGE_URI=$ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPOSITORY:latest
        kubectl set image deployment/devsecops-java-app devsecops-java-app=$IMAGE_URI -n ${{ env.K8S_NAMESPACE }}
        kubectl rollout status deployment/devsecops-java-app -n ${{ env.K8S_NAMESPACE }}
